import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createTheme, CssBaseline, ThemeProvider } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
});

export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={darkTheme}>
      <CssBaseline />
      {/* <script
        async
        src="https://cse.google.com/cse.js?cx=57d3aa7026aa34170"
      ></script> */}

      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      {/* <div className="gcse-searchresults-only">{children}</div> */}
      <main>{children}</main>
      {/* </body> */}
    </ThemeProvider>
  );
}
